### PR TITLE
Add `posv`

### PR DESCRIPTION
**Pull request by jmh530**

### CODE REVIEW

**Comment by 9il** [comment]
please tag if needed

**Comment by jmh530** [comment]
@9il Done.

**Comment by jmh530** [comment]
@9il BTW, WebFreak001 [recommended](https://github.com/dlang/dub-registry/issues/556#issuecomment-1839485476) that I ask for access to "Allow triggering manual updates" in code.dlang.org for some of these mir projects.

**Comment by 9il** [comment]
I can deregister mir-stat from code dlang so you can register it yourself.

Can I "Allow triggering manual updates" without deregistering for other packages?

**Comment by jmh530** [comment]
@9il I don't have an issue with that, but I would trust your judgement as to what is appropriate. I haven't done it myself, but if you log in to code.dlang.org and go into the package and select permissions there is an option to add a user and that's where the option to "Allow triggering manual updates" is. So you'd just add me there, select the box, and save and that should be it. There are other options too (might make sense to be an admin for mir-stat, but just the permission to trigger manual updates for some of the others).

image

**Comment by 9il** [comment]
@jmh530 What is your username on code.dlang.org?

**Comment by jmh530** [comment]
jmh530 as well

**Comment by 9il** [comment]
Cool, I have added all permissions for mir-stat and triggering permissions for core, algorithm, and ion.

**Comment by jmh530** [comment]
Thanks!

**Comment by jmh530** [comment]
@9il Maybe makes sense to add mir-blas, mir-lapack, mir-random as well.

**Comment by jmh530** [comment]
@9il ping

**Comment by 9il** [comment]
done

**Comment by jmh530** [comment]
@9il Thanks!

**Pull request merged**
